[package]
name = "runpod"
version = "0.1.27"
edition = "2021"
description = "A Rust client for the RunPod API"
license = "MIT"
repository = "https://github.com/agentsea/runpod.rs"
documentation = "https://docs.rs/runpod"
readme = "README.md"
keywords = ["runpod", "api-client", "gpu", "cloud"]
categories = ["api-bindings", "web-programming::http-client"]

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.40"